spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

logging:
  config: classpath:log4j2.xml
  level: info